"""Initial

Revision ID: f44c227e9ca4
Revises: 
Create Date: 2022-02-09 21:44:57.993271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f44c227e9ca4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('serie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('season',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num_episodes', sa.Integer(), nullable=True),
    sa.Column('first_aired', sa.String(length=60), nullable=True),
    sa.Column('local_aired', sa.String(length=60), nullable=True),
    sa.Column('serie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['serie_id'], ['serie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('episode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_title', sa.String(length=120), nullable=False),
    sa.Column('local_title', sa.String(length=120), nullable=True),
    sa.Column('first_aired', sa.DateTime(), nullable=True),
    sa.Column('local_aired', sa.DateTime(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('episode')
    op.drop_table('season')
    op.drop_table('serie')
    # ### end Alembic commands ###
